openapi: "3.0.0"
info:
  title: "Task API"
  description: "API for managing tasks"
  version: "1.0.0"
paths:
  /tasks/{taskId}:
    delete:
      summary: "Delete a task"
      description: "Delete a task by its ID"
      parameters:
        - name: "taskId"
          in: "path"
          description: "ID of the task to delete"
          required: true
          schema:
            type: "integer"
      responses:
        '201':
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "Task removed successfully"
        '400':
          description: "Task is completed or other error"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"
                    example: "Task is completed"
        '403':
          description: "Access denied"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"
                    example: "Access denied"
        '404':
          description: "Task not found"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"
                    example: "Task not found"